
DROP DATABASE DULICHVIETNAM
CREATE DATABASE DULICHVIETNAM
GO
USE DULICHVIETNAM
CREATE TABLE QUYEN(
	MaQuyen INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenQuyen NVARCHAR(50) NULL
)

CREATE TABLE ADMIN(
	TenDNAdmin NVARCHAR(50) NOT NULL PRIMARY KEY,
	MK VARCHAR(50) NULL,
	HoTen NVARCHAR(100) NULL,
	MaQuyen INT NULL,
	FOREIGN KEY(MaQuyen) REFERENCES dbo.Quyen(MaQuyen)
)

CREATE TABLE KHACHHANG(
	MaKH INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenKH NVARCHAR(100) NULL,
	NgaySinh date NULL,
	GioiTinh INT NULL,
	SDT VARCHAR(12) NULL,
	Email NVARCHAR(255) NULL,
	TenDN VARCHAR(50) UNIQUE,
	MK VARCHAR(50) NULL,
	MaQuyen INT NULL,
	FOREIGN KEY(MaQuyen) REFERENCES dbo.QUYEN(MaQuyen)
)
GO

CREATE TABLE KHACHSAN(
	MaKS INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenKS NVARCHAR(100) NULL,
	DiaChi NVARCHAR(255) NULL,
	SoPhong INT NULL
)
GO

CREATE TABLE LOAIPHONG(
	MaLP INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenLoai NVARCHAR(100) NULL,
	GiaPhongDon FLOAT NOT NULL,
	GiaPhongDoi FLOAT NOT NULL,
	MaKS INT NULL,
	FOREIGN KEY(MaKS) REFERENCES dbo.KHACHSAN(MaKS)
)
GO

CREATE TABLE PHUONGTIEN(
	MaPT INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenPT NVARCHAR(100) NULL,
	SoCho INT NULL,
	BienKS VARCHAR(50) NULL
)
GO

CREATE TABLE TINHTHANH(
	MaTT INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenTT NVARCHAR(100) NULL,
	HinhAnh NVARCHAR(MAX) NULL
)
GO

CREATE TABLE HUONGDANVIEN(
	MaHDV INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenHDV NVARCHAR(100) NULL,
	SDT VARCHAR(12) NULL,
	DiaChi NVARCHAR(255) NULL
)
GO

CREATE TABLE TOUR(
	MaTour INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenTour NVARCHAR(255) NULL,
	GiaTour FLOAT NOT NULL,
	SoLuong INT NULL,
	NgayKhoiHanh DATE NULL,
	ThoiGianNgay FLOAT NULL,
	ThoiGianDem FLOAT NULL,
	DichVu NVARCHAR(max) NULL,
	HinhAnh1 NVARCHAR(max) NULL,
	HinhAnh2 NVARCHAR(max) NULL,
	HinhAnh3 NVARCHAR(max) NULL,
	HinhAnh4 NVARCHAR(max) NULL,
	HanhTrinh NVARCHAR(max) NULL,
	NoiXuatPhat NVARCHAR(max) NULL,
	TiLe FLOAT NOT NULL,
	MaTT INT NULL,
	MaPT INT NULL,
	MaHDV INT NULL,
	FOREIGN KEY(MaTT) REFERENCES dbo.TINHTHANH(MaTT),
	FOREIGN KEY(MaPT) REFERENCES dbo.PHUONGTIEN(MaPT),
	FOREIGN KEY(MaHDV) REFERENCES dbo.HUONGDANVIEN(MaHDV)
)
GO

CREATE TABLE HUONGDANVIEN(
	MaHDV INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenHDV NVARCHAR(100) NULL,
	SDT VARCHAR(12) NULL,
	DiaChi NVARCHAR(100) NULL
)
GO
CREATE TABLE DATTOUR(
	MaTour INT NOT NULL,
	MaKH INT NOT NULL,
	SoLuongNL INT NULL,
	SoLuongTE INT NULL,
	NgayDat DATE NULL,
	MaLP INT NULL,
	SoPhongDon INT NULL,
	SoPhongDoi INT NULL,
	YeuCau NVARCHAR(max) NULL,
	TongTien FLOAT NULL,
	FOREIGN KEY(MaTour) REFERENCES dbo.TOUR(MaTour),
	FOREIGN KEY(MaKH) REFERENCES dbo.KHACHHANG(MaKH),
	FOREIGN KEY(MaLP) REFERENCES dbo.LOAIPHONG(MaLP)
)

CREATE TABLE NHANVIEN(
	MaNV INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenNV NVARCHAR(100) NULL,
	ChucVu NVARCHAR(100) NULL,
	Facebook NVARCHAR(MAX) NULL,
	Twitter NVARCHAR(MAX) NULL,
	Gmail NVARCHAR(MAX) NULL
)

CREATE TABLE CHUDE(
	MaCD INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenCD NVARCHAR(MAX) NULL
)

CREATE TABLE LIENHE(
	MaLH INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(100) NULL,
	Email NVARCHAR(255) NULL,
	MaCD INT NULL,
	TinNhan NVARCHAR(MAX) NULL,
	FOREIGN KEY(MaCD) REFERENCES dbo.CHUDE (MaCD)
)

CREATE TABLE CHINHANH(
	MaCN INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenCN NVARCHAR(100) NULL,
	DiaChi NVARCHAR(MAX) NULL,
	Email NVARCHAR(MAX) NULL,
	DienThoai NVARCHAR(12) NULL
)

CREATE TABLE TRANGCHU(
	AnhSlide1 NVARCHAR(MAX) NULL,
	AnhSlide2 NVARCHAR(MAX) NULL,
	AnhSlide3 NVARCHAR(MAX) NULL,
	AnhSlide4 NVARCHAR(MAX) NULL,
	LoiHuaHen NVARCHAR(MAX) NULL,
	Video NVARCHAR(MAX) NULL,
)

CREATE TABLE DIEMDEN(
	MaDD INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenDD NVARCHAR(100) NULL,
	HinhAnh NVARCHAR(MAX) NULL,
)

CREATE TABLE GIOITHIEU(
	TomTat NVARCHAR(MAX) NULL,
	LiDoLuaChon NVARCHAR(MAX) NULL,
	ChamNgon1 NVARCHAR(MAX) NULL,
	ChamNgon2 NVARCHAR(MAX) NULL,
	ChamNgon3 NVARCHAR(MAX) NULL,
	ChamNgon4 NVARCHAR(MAX) NULL
)

CREATE TABLE FOOTER(
	LoiMoi NVARCHAR(MAX) NULL,
	Facebook NVARCHAR(MAX) NULL,
	Insta NVARCHAR(MAX) NULL,
	Twitter NVARCHAR(MAX) NULL,
	Gmail NVARCHAR(MAX) NULL,
	Git NVARCHAR(MAX) NULL,
	Anh1 NVARCHAR(MAX) NULL,
	Anh2 NVARCHAR(MAX) NULL,
	Anh3 NVARCHAR(MAX) NULL,
	Anh4 NVARCHAR(MAX) NULL,
	Anh5 NVARCHAR(MAX) NULL,
	Anh6 NVARCHAR(MAX) NULL
)

